config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'static_pages#home'
  get 'musics/search', to: 'musics#search', as: 'search_musics'
  get 'musics/songs', to: 'musics#songs', as: 'songs_musics'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    get     'signup' => 'users/registrations#new'
    post    'signup' => 'users/registrations#create'
    get     'login'  => 'users/sessions#new'
    post    'login'  => 'users/sessions#create'
    delete 'logout'  => 'users/sessions#destroy'
  end
  resources :users, :only => [:index, :show] do
    resources :footprints, only: [:index, :create]
    collection do
      get :search
    end
  end
  resources :rooms, :only => [:index, :show, :create, :destroy]
  resources :messages, :only => [:create]
  resources :articles, :only => [:index, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
    member do
      get :renew
    end
    collection do
      get :likes
    end
  end
  resources :recruitment_articles, :only => [:index, :new, :create, :edit, :update] do
    collection do
      get :search
    end
  end
  resources :join_articles, :only => [:index, :new, :create, :edit, :update] do
    collection do
      get :search
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])
  def home
    @users = User.limit(3).order("created_at DESC")
    @recruitment_articles = Article.where(type: 'メンバー募集').limit(3).
      order("created_at DESC").includes([:user])
    @join_articles = Article.where(type: '加入希望').limit(3).
      order("created_at DESC").includes([:user])
    if Rails.env.development? || Rails.env.production?
      featured_playlists = RSpotify::Playlist.browse_featured(country: 'JP')
      @featured_playlist = featured_playlists[1]
      @featured_playlist_tracks = featured_playlists[1].tracks.sample(15)
    end
    if current_user
      @recommended_users = User.where(favorite_music: current_user.favorite_music).
        where.not(id: current_user.id).limit(3).order("created_at DESC")
    end
  end
end

app/views/static_pages/_home_side_bar.html.erb
<div class="home-side-bar-wrapper">
  <% if featured_playlist.present? %>
    <div class="home-side-bar">
      <div class="chart-name">
        <p>現在のチャート:<span style="color: orange;"><%= featured_playlist.name %></span></p>
        <p style="font-size: 12px;">曲をクリックすると試聴できます(一部制限あり)</p>
      </div>
      <% featured_playlist_tracks.each do |track| %>
        <div class="chart-artist">
          <div><%= display_artist_image(track.artists.first,2) %></div>
          <div class="chart-artist-info">
            <div><%= track.artists.first.name %></div>
            <div><%= link_to track.name, track.preview_url %></div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= render 'member_registration' %>
</div>

app/views/static_pages/_member_registration.html.erb
<% unless current_user %>
  <div class="member-registration-wrapper">
    <div class="member-registration">
      <p style="font-weight: bold;">新規会員登録</p>
      <p style="color: gray;">ログインするとメンバー募集記事を出したり、ユーザー同士のチャットができるようになります</p>
      <p class="text-center"><%= link_to '会員登録', signup_path, class: 'btn btn-primary' %></p>
    </div>
  </div>
<% end %>

app/views/static_pages/_service_description_box.html.erb
<div class="service-description-box">
  <div>
    <ol>
      <li class="text-center">
        <span style="color: orange;">G</span>
        <span style="color: #0645AD;">roove</span>
        <span style="color: orange;">W</span>
        <span style="color: #0645AD;">ith!</span>
        でバンドメンバー探しを始めよう!
      </li>
      <li>まずは新規登録ページからアカウントを作成しよう！</li>
      <li>検索機能で気になる記事やユーザーを探してみよう！</li>
      <li>実際にメンバー募集や加入希望記事を書いてみよう！</li>
      <li>足跡機能で自分の記事に興味を持った人をチェック！</li>
      <li>バンドを組む約束をしたら最後に練習曲を決めよう！</li>
    </ol>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="home-wrapper"> 
  <div class="home-main-block">
    <%= render 'service_description_box' %>
    <h3 class="page-title">新着メンバー<span class="new-mark">New!</span></h3>
    <div><%= render @users %></div>
    <div class='edit_link'>
      <%= link_to '条件を絞ってメンバーを探す', users_path, class: 'btn btn-default' %>
    </div>
    <h3 class="page-title">新着メンバー募集記事<span class="new-mark">New!</span></h3>
    <div><%= render @recruitment_articles %></div>
    <div class='edit_link'>
      <%= link_to '条件を絞ってメンバー募集記事を探す', recruitment_articles_path, class: 'btn btn-default' %>
    </div>
    <h3 class="page-title">新着加入希望記事<span class="new-mark">New!</span></h3>
    <div><%= render @join_articles %></div>
    <div class='edit_link'>
      <%= link_to '条件を絞って加入希望記事を探す', join_articles_path, class: 'btn btn-default' %>
    </div>
    <% if current_user %>
      <h3 class="page-title"><%= current_user.favorite_music %>が好き！</h3>
      <div class='recommended_users'><%= render @recommended_users %></div>
    <% end %>
  </div>
  <%= render 'home_side_bar', featured_playlist: @featured_playlist, featured_playlist_tracks: @featured_playlist_tracks %>
</div>