config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'static_pages#home'
  get 'musics/search', to: 'musics#search', as: 'search_musics'
  get 'musics/songs', to: 'musics#songs', as: 'songs_musics'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    get     'signup' => 'users/registrations#new'
    post    'signup' => 'users/registrations#create'
    get     'login'  => 'users/sessions#new'
    post    'login'  => 'users/sessions#create'
    delete 'logout'  => 'users/sessions#destroy'
  end
  resources :users, :only => [:index, :show] do
    resources :footprints, only: [:index, :create]
    collection do
      get :search
    end
  end
  resources :rooms, :only => [:index, :show, :create, :destroy]
  resources :messages, :only => [:create]
  resources :articles, :only => [:index, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
    member do
      get :renew
    end
    collection do
      get :likes
    end
  end
  resources :recruitment_articles, :only => [:index, :new, :create, :edit, :update] do
    collection do
      get :search
    end
  end
  resources :join_articles, :only => [:index, :new, :create, :edit, :update] do
    collection do
      get :search
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true, length: { maximum: 1000 }
  scope :recent, -> { order(created_at: :desc) }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = current_user.messages.build(message_params)
    @room = @message.room
    if @message.save
      @message.room.update(last_message_created_at: DateTime.now)
      flash[:success] = 'メッセージを送信しました'
      MessageMailer.send_mail(@message, get_companion_to_talk_with).deliver_now
      redirect_to room_path(@message.room.id)
    else
      @messages = @room.messages.order(created_at: :desc).limit(10).includes([:user])
      render template: 'rooms/show'
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :room_id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def message_already_read(message)
    if message.already_read
      '既読'
    else
      '未読'
    end
  end
end

app/views/messages/_message.html.erb
<div class="all-messages">
  <% if message.user == current_user %>
    <div class='my-messages'>
      <p class="message-content"><%= message.content %></p>
    </div>
    <span class="my-messege-created-time">
      <%= message_already_read(message) %>
      <%= message.created_at.strftime('%Y/%m/%d %H:%M') %>
    </span>
  <% else %>
    <div class="talker-messages">
      <div style="margin-top: 5px;">
        <%= link_to user_path(message.user) do %>
          <%= set_user_avatar(message, 75) %>
        <% end %>
      </div>
      <ul class="user-info">
        <li class="user-name"><%= message.user.name %></li>
        <li class="talker-message-content"><%= message.content %></li>
        <li><%= message.created_at.strftime('%Y/%m/%d %H:%M') %></li>
      </ul>
    </div>
  <% end %>
</div>