config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'static_pages#home'
  get 'musics/search', to: 'musics#search', as: 'search_musics'
  get 'musics/songs', to: 'musics#songs', as: 'songs_musics'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    get     'signup' => 'users/registrations#new'
    post    'signup' => 'users/registrations#create'
    get     'login'  => 'users/sessions#new'
    post    'login'  => 'users/sessions#create'
    delete 'logout'  => 'users/sessions#destroy'
  end
  resources :users, :only => [:index, :show] do
    resources :footprints, only: [:index, :create]
    collection do
      get :search
    end
  end
  resources :rooms, :only => [:index, :show, :create, :destroy]
  resources :messages, :only => [:create]
  resources :articles, :only => [:index, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
    member do
      get :renew
    end
    collection do
      get :likes
    end
  end
  resources :recruitment_articles, :only => [:index, :new, :create, :edit, :update] do
    collection do
      get :search
    end
  end
  resources :join_articles, :only => [:index, :new, :create, :edit, :update] do
    collection do
      get :search
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :likes, foreign_key: :article_id, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  validates :type, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :instrument, presence: true
  validates :prefecture, presence: true
  validates :description, presence: true, length: { maximum: 2000 }
  enum type: { メンバー募集: 0, 加入希望: 1 }
  self.inheritance_column = :_type_disabled

  def renew_of_once_a_day?
    created_at = self.created_at
    difference_time = Time.zone.now - created_at
    difference_time / 3600 >= 24
  end

  def set_instrument_as_string
    if valid?
      instruments = instrument
      instrument_array = instruments.split(',').map { |m| m.delete('[]"\\\\') }
      self.instrument = instrument_array.join(",")
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:destroy, :renew, :likes]
  before_action :correct_user, only: [:destroy, :renew]

  def index
    @q = Article.order(created_at: :desc).includes([:user]).ransack(params[:q])
    @articles = @q.result(distinct: true).page(params[:page]).per(20)
  end

  def show
    @article = Article.find(params[:id])
    @like = Like.new
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:success] = '記事を削除しました'
      redirect_to user_path(current_user)
    else
      redirect_to root_url
    end
  end

  def renew
    @article = Article.find(params[:id])
    if @article.renew_of_once_a_day?
      @article.created_at = Time.zone.now.to_s
      @article.save
      flash[:success] = '記事を更新しました'
      redirect_to root_path
    else
      flash[:danger] = '更新に失敗しました。更新は24時間に1回までとなります'
      redirect_to article_path(@article)
    end
  end

  def likes
    @articles = current_user.liked_articles.page(params[:page]).includes([:user]).per(20)
  end

  private

  def search_params
    params.require(:q).permit(:title_cont, :instrument_cont,
                              :prefecture_cont, :age_cont, :gender_cont)
  end

  def article_params
    params.require(:article).permit(:type, :title, :description,
                                    :prefecture, :gender, :age, instrument: [])
  end
end

app/views/articles/_article.html.erb
<div class="articles">
  <div class='users toggle'>
    <div style="margin-top: 5px;"><%= set_user_avatar(article, 75)%></div>
    <ul class='user-info' style="color: black;">
      <li class='article-title'>   
        <% if article.type == 'メンバー募集'%>
          <span class='recruitment-mark'>(募)</span>
        <% else %>
          <span class='join-mark'>(加)</span>
        <% end %>
        <%= article.title %>
      </li>
      <li>
        名前:<%= article.user.name %>,
        活動場所:<%= article.prefecture %>
      </li>
      <li>
        年齢:<%= article.user.age %>代,
        性別:<span class= <%= set_gender(article)%>><%= article.user.gender %><span>
      </li>
    </ul>
  </div>
  <div class="self_introduction">
    <p style="font-weight:bold;">【詳細】</p>
    <pre><%= article.description %></pre>
    <div class="reader-actions">
      <div class=reader-action-box>
        <%= link_to article_path(article) do %>
          <div><i class = "fa fa-file-text fa-2x"></i></div>
          <div>記事の詳細</div>
        <% end %>
      </div>
      <% if current_user == article.user %>
        <div class=reader-action-box>
          <%= link_to edit_join_article_path(article) do %>
            <div class="message-link">
              <div><i class="fa fa-edit fa-2x"></i></div>
              <div>記事の編集</div>
            </div>
          <% end %>
        </div>
      <% else%>
        <div class=reader-action-box>
          <%= link_to rooms_path(talker_id: article.user.id), method: :post do %>
            <div class="message-link">
              <div><i class="fa fa-envelope fa-2x"></i></div>
              <div>メッセージ</div>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="reader-action-box slide_up">
        <div><i class = "fa fa-times-circle fa-2x"></i></div>
        <div>閉じる</div>
      </div>
    </div>
  </div>
</div>

app/views/articles/_author_actions.html.erb
<div class="reader-actions">
  <div class=reader-action-box>
    <% if article.type == "メンバー募集" %>
      <%= link_to edit_recruitment_article_path(article) do %>
        <div><i class="fa fa-edit fa-3x"></i></div>
        <div>記事の編集</div>
      <% end %>
    <% else %>
      <%= link_to edit_join_article_path(article) do %>
        <div><i class="fa fa-edit fa-3x"></i></div>
        <div>記事の編集</div>
      <% end %>
    <% end %>
  </div>
  <div class=reader-action-box>
    <%= link_to renew_article_path(article) do %>
      <div><i class="fa fa-file fa-3x"></i></div>
      <div>記事の更新</div>
    <% end %>
  </div>
  <div class=reader-action-box>
    <%= link_to "/articles/#{article.id}", method: :delete, data: {confirm: "記事を本当に削除しますか？"} do %>
      <div><i class="fa fa-trash fa-3x"></i></div>
      <div>記事の削除</div>
    <% end %>
  </div>
</div>

app/views/articles/_logged_in_user_actions.html.erb
<div class="reader-actions">
  <div class=reader-action-box id="likes_buttons">
    <%= render partial: 'likes/like', locals: { article: article } %>
  </div>
  <div class=reader-action-box>
    <%= link_to user_path(article.user) do %>
      <div><i class = "fa fa-user fa-3x"></i></div>
      <div>プロフィール</div>
    <% end %>
  </div>
  <div class=reader-action-box>
    <%= link_to rooms_path(talker_id: article.user.id), method: :post do %>
      <div class="message-link">
        <div><i class="fa fa-envelope fa-3x"></i></div>
        <div>メッセージ</div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_reader_actions.html.erb
<% if current_user == article.user %>
  <%= render 'author_actions', article: @article %>
<% elsif user_signed_in? %>
  <%= render 'logged_in_user_actions', article: @article %>
<% else %>
  <div class='edit_link'>
    <%= link_to 'ログインしてメッセージを送る', rooms_path(talker_id: article.user.id), method: :post, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/articles/index.html.erb
<% provide(:title, '記事一覧') %>
<h3 class="page-title">記事一覧</h3>
<p><%= link_to 'メンバー募集記事を検索はこちら', recruitment_articles_path %></p>
<p><%= link_to '加入希望記事を検索はこちら', join_articles_path %></p>
<div><%= render @articles %></div>
<div class="text-center"><%= paginate @articles %></div>

app/views/articles/likes.html.erb
<% provide(:title, 'お気に入りの記事') %>
<h3 class="page-title">お気に入りの記事</h3>
<div><%= render @articles %></div>
<div class="text-center"><%= paginate @articles %></div>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<h3 class="page-title"><%= @article.title %></h3>
<div class='article-section'>
  <p class="article-section-title">記事の内容</p>
  <p class='introduction_letter'><%= @article.description %></p>
</div>
<div class='article-section'>
  <p class="article-section-title">基本情報</p>
  <ul>
    <li>記事のタイプ:<%= @article.type %></li>
    <li>活動場所:<%= @article.prefecture %></li>
    <li>加入希望のパート:<%= @article.instrument %></li>
  </ul>
</div>
<div class='article-section'>
  <p class="article-section-title">投稿者情報</p>
  <ul>
    <li><%= set_user_avatar(@article, 100)%></li>
    <li>名前:<%= @article.user.name %></li>
    <li>年齢:<%= @article.user.age %>代</li>
    <li>性別:<span class= <%= set_gender(@article)%>><%= @article.user.gender %><span></li>
    <li>担当パート:<%= @article.user.instrument %></li>
    <li><%= link_to '詳しくプロフィールを見る', user_path(@article.user) %></li>
  </ul>
</div>
<%= render 'reader_actions', article: @article %>