config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'static_pages#home'
  get 'musics/search', to: 'musics#search', as: 'search_musics'
  get 'musics/songs', to: 'musics#songs', as: 'songs_musics'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    get     'signup' => 'users/registrations#new'
    post    'signup' => 'users/registrations#create'
    get     'login'  => 'users/sessions#new'
    post    'login'  => 'users/sessions#create'
    delete 'logout'  => 'users/sessions#destroy'
  end
  resources :users, :only => [:index, :show] do
    resources :footprints, only: [:index, :create]
    collection do
      get :search
    end
  end
  resources :rooms, :only => [:index, :show, :create, :destroy]
  resources :messages, :only => [:create]
  resources :articles, :only => [:index, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
    member do
      get :renew
    end
    collection do
      get :likes
    end
  end
  resources :recruitment_articles, :only => [:index, :new, :create, :edit, :update] do
    collection do
      get :search
    end
  end
  resources :join_articles, :only => [:index, :new, :create, :edit, :update] do
    collection do
      get :search
    end
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])

  def search
    @artist = RSpotify::Artist.search(params[:search]).first if params[:search].present?
    if @artist
      @related_artists = @artist.related_artists
      @albums = @artist.albums
    end
  end

  def songs
    @tracks = RSpotify::Track.search(params[:search])[0..3] if params[:search].present?
    unless @tracks
      default_tracks_ids = [
        '23atyJacJVHvB9RHBNhr35', '4gWZCG6mEKH0LlMAed01ga',
        '6CAPCLuAa9hb2MBdZXOhep', '77LQNv3wdUvN5sXG9v5H9u',
      ]
      @tracks = default_tracks_ids.map { |n| RSpotify::Track.find(n) }
    end
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
  def display_artist_image(artist, number)
    if artist && artist.images.any?
      image = artist.images[number]
      image_tag(image["url"])
    else
      image_tag("default.jpg")
    end
  end

  def track_key(number)
    key_array = ['C', 'C#', 'D', 'E♭', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
    key_array[number]
  end

  def track_mode(number)
    if number == 0
      "マイナー"
    else
      "メジャー"
    end
  end

  def track_score(number)
    "#{number.to_i}点/100点"
  end

  def track_info_graf(number)
    if number > 75
      "background-color:#FFAD90;width:#{number}%;"
    elsif number > 35
      "background-color:#FFFACD;width:#{number}%;"
    else
      "background-color:#87CEFA;width:#{number}%;"
    end
  end

  def track_feature_points(track)
    features = ['danceability', 'acousticness', 'energy', 'speechiness', 'valence']
    features_jp = ['躍りやすさ:', 'アコースティック感:', '曲の激しさ:', 'ポエトリー度:', '曲のポジティブ度:']
    features_points = features.map { |n| (track.audio_features.send(n) * 100).to_i }
    [features_jp, features_points].transpose.to_h
  end
end

app/views/musics/_artist_info_inner.html.erb
<% if artist %>
  <div class="artist-info-inner">
    <h3><%= artist.name %></h3>
    <%= display_artist_image(artist,1) %>
    <h3>ジャンル</h3>
    <ul class="music-genres">
      <% artist.genres.each do |genre| %>
        <li><%= genre %></li>
      <% end %>
    </ul>
    <h3>アルバム</h3>
    <p style="color: orange;">＊アルバムをクリックすると収録曲を確認できます</p>
    <% if albums %>
      <% albums.each do |album| %>
        <p class="toggle"><%= album.name %></p>
        <ul class="tracks">
          <p style="color: orange;">＊曲名をクリックすると試聴することができます</p>
          <% album.tracks.each do |track| %>
            <li><%= link_to track.name, track.preview_url %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/musics/_artists_for_beginners.html.erb
<% artists = ["モンゴル800", "Green Day", "yonige", "Chatmonchy"] %>
<div class="artists-for-beginners">
  <h3>初心者におすすめのアーティスト</h3>
  <p style="color: orange;">＊初心者でもコピーしやすいバンドはこちら！</p>
  <ul>
    <% artists.each do |artist| %>
      <li>
        <%= form_with url: search_musics_path, method: :get, local: true do |form| %>
          <%= form.hidden_field :search, value: artist%>
          <%= form.submit artist %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/musics/_artists_search_form.html.erb
<div>
  <%= form_with url: search_musics_path, method: :get, local: true do |form| %>
    <%= form.text_field :search, placeholder: "アーティスト名で検索", class: "music-search-text-field" %>
    <%= form.submit '検索' %>
  <% end %>
</div>

app/views/musics/_related_artists.html.erb
<div class="related-artist-wrapper">
  <h3>関連アーティスト</h3>
  <% if related_artists.present? %>
    <div class="related_artist">
      <% related_artists.each do |related_artist| %>
        <%= form_with url: search_musics_path, method: :get, local: true do |form| %>
          <%= form.hidden_field :search, value: related_artist.name %>
          <%= button_tag :type => "submit" do %>
            <div class="related_artist_name">
              <%= display_artist_image(related_artist,2) %>
              <%= related_artist.name %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/musics/search.html.erb
<% provide(:title, 'アーティストを検索') %>
<h3 class="page-title">アーティストを検索して練習曲を決めよう</h3>
<div class="artists-search-form-responsive"><%= render 'artists_search_form' %></div>
<div class="artist-page">
  <div class="artist-info">
    <%= render 'artists_for_beginners' %>
    <%= render 'artist_info_inner', artist: @artist, albums: @albums %>
    <div class="artists-for-beginners">
      <h3>練習曲を探そう</h3>
      <p>バンドメンバーが集まったら、次は練習曲を決めてみませんか？</p>
      <p>初心者の場合は上記の4つのバンドから練習曲を決めるのがおすすめです！</p>
      <p><%= link_to 'おすすめ練習曲はこちら', songs_musics_path %></p>
    </div>
  </div>
  <div>
    <span class="artists-search-form-pc"><%= render 'artists_search_form' %></span>
    <%= render 'related_artists', related_artists: @related_artists %>
  </div> 
</div>

app/views/musics/songs.html.erb
<% provide(:title, '初心者向けおすすめ練習曲') %>
<h3 class="page-title">初心者向けおすすめ練習曲</h3>
<div class="text-center">
  <%= form_with url: songs_musics_path, method: :get, local: true do |form| %>
    <%= form.text_field :search, placeholder: "曲名から検索", class: "music-search-text-field" %>
    <%= form.submit '検索' %>
  <% end %>
</div>
<div class="tracks-info">
  <% if @tracks %>
    <% @tracks.each do |track| %>
      <div class="track-basic-info">
        <p><%= display_artist_image(track.artists.first, 1) %></p>
        <ul class="chart-artist-info">
          <li>アーティスト名:<%= track.artists.first.name %></li>
          <li><%= link_to track.name, track.preview_url %></li>
          <li>曲の長さ:<%= Time.at(track.audio_features.duration_ms / 1000).utc.strftime('%X') %></li>
          <li>BPM/テンポ:<%= track.audio_features.tempo.to_i %></li>
          <li>曲のキー/主和音:<%= track_key(track.audio_features.key) %><%= track_mode(track.audio_features.mode) %></li>
        </ul>
      </div>
      <ul class="track-additional-info">
        <% track_feature_points(track).each do |key, value| %>
          <li class="track_graph" style=<%= track_info_graf(value) %>><span class="track_graph_label"><%= key %><%= track_score(value) %></span></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>